env: prod
component: catalogue
params: "DOCUMENTDB:prod.catalogue.mongo,MONGO_URL:prod.docdb.url.catalogue"

schemaLoadJob:
  create: true
  type: mongo

resources:
  limits:
    cpu: 100m
    memory: 350Mi
  requests:
    cpu: 200m
  memory: 256Mi